name: Test sphinx docs and landing page build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'
  workflow_dispatch: {}
jobs:
    changes:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4

    test:
      name: Test sphinx docs and landing page build
      runs-on: ubuntu-latest
      env:
          UV_FROZEN: 1
      steps:
        - uses: actions/checkout@v4
          with:
            submodules: true

        - uses: extractions/setup-just@v3
          with:
            just-version: '1.40.0'

        - uses: actions/setup-node@v4
          with:
            node-version: '22'

        - name: Install uv
          uses: astral-sh/setup-uv@v5
          with:
              enable-cache: true
              version: "0.6.6"

        - name: Run the docs build (includes landing page)
          run: |
            just build
            # just coverage
            just link-check


